### ISSUE TITLE
Upgrade to Java 11

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/model#280]
- [x] Upgrade Java version in `pom.xml`
- [x] Upgrade Java version in GitHub workflows

**Comment by SanjayRam07** [comment]
Is this issue still open. can I work on this?

**Comment by pedinil** [comment]
I am available to work on it

**Comment by SanjayRam07** [comment]
> I am available to work on it

Okkayy, thank you. Inform if I can work on this

**Comment by nya-elimu** [comment]
> Is this issue still open. can I work on this?

@SanjayRam07 @pedinil Yes, you are welcome to work on this issue 🙂

I invited you both as members of the GitHub organization (check your e-mail) so that you get access to assign yourselves to issues.

**Comment by nya-elimu** [comment]
@SanjayRam07 Thank you for coding the #281 pull request 🙂

Can you please also upgrade the Java version used in the workflow files at [`maven-build.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-build.yml) and [`maven-release.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-release.yml)?

**Comment by SanjayRam07** [comment]
> @SanjayRam07 Thank you for coding the #281 pull request 🙂
> 
> Can you please also upgrade the Java version used in the workflow files at [`maven-build.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-build.yml) and [`maven-release.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-release.yml)?

Yeah, I need to update Java version. I'll work on this and run the workflow.

**Comment by SanjayRam07** [comment]
> @SanjayRam07 Thank you for coding the #281 pull request 🙂
> 
> Can you please also upgrade the Java version used in the workflow files at [`maven-build.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-build.yml) and [`maven-release.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-release.yml)?

**Comment by SanjayRam07** [comment]
> @SanjayRam07 Thank you for coding the #281 pull request 🙂
> 
> Can you please also upgrade the Java version used in the workflow files at [`maven-build.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-build.yml) and [`maven-release.yml`](https://github.com/elimu-ai/model/blob/main/.github/workflows/maven-release.yml)?


I have updated, kindly review it to merge it into main branch

**Comment by nya-elimu** [comment]
> I have updated, kindly review it to merge it into main branch

Reviewed, looks good 👍🏽
